@startuml element

class Element {
    + innerHTML: html de los nodos descendientes serialized as string
    + classList: DOMTokenList

    + setAttribute(attribute: String, value: String);
    + setAttributeNode(Attr)
}
Node <|-- Element

class HTMLElement 
Element <|-- HTMLElement

class HTMLInputElement 
HTMLElement <|-- HTMLInputElement
HTMLElement *--> CSSStyleDeclaration: + style

class HTMLFormElement
HTMLElement <|-- HTMLFormElement

class CSSStyleDeclaration
@enduml
