@startuml element

class Element {
    + innerHTML: html de los nodos descendientes serialized as string

    + setAttribute(attribute: String, value: String);
    + setAttributeNode(Attr)
}
Node <|-- Element

class HTMLElement 
Element <|-- HTMLElement
Element --> CSSStyleDeclaration: + style

class HTMLInputElement {
    + value
}
HTMLElement <|-- HTMLInputElement

class CSSStyleDeclaration
@enduml
